[shell]
program = "/usr/bin/bash"
args = ["tmux"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"


[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[mouse]
[keyboard]
